## q-1-1-2

In [1]:
import numpy as np
from numpy import log2 as log
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
import operator
import sys

In [2]:
# filename = sys.argv[1]
filename = "iris"
def loadfile(file_name):
    if file_name=="iris":
        filename = 'input_data/Iris.csv'
        df = pd.read_csv(filename, names = ["a", "b", "c", "d", "Y"])
    elif file_name=="robot1":
        filename = 'input_data/Robot1'
        df = pd.read_csv(filename, delim_whitespace=True, names = ["Y", "a", "b", "c", "d", "e", "f", "g"])
        df = df.drop(['g'],axis=1)
    else:
        filename = 'input_data/Robot2'
        df = pd.read_csv(filename, delim_whitespace=True, names = ["Y", "a", "b", "c", "d", "e", "f", "g"])
        df = df.drop(['g'],axis=1)
    return df

df = loadfile(filename)

In [3]:
Y = df.Y
labels = Y.unique()
X = df.drop(['Y'], axis=1)
if filename != "iris":
    X = pd.DataFrame(preprocessing.normalize(X), columns = ["a","b", "c", "d", "e", "f"])

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.2)
df1 = pd.concat([X_train, Y_train],axis=1).reset_index(drop=True)

neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train, Y_train)
p = neigh.predict(X_test)
print confusion_matrix(Y_test,p)
print classification_report(Y_test,p)
print accuracy_score(Y_test,p)

In [5]:
def manhattan_distance(x, y):   
    return np.sum(abs(x, y))

In [6]:
def cosine_similarity(x, y):
    print x
    print y
    return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

In [7]:
def euclidean_distance(x, y):   
    return np.sqrt(np.sum((x - y) ** 2))

In [8]:
def distance(x, y, flag):
    if flag==1:
        return euclidean_distance(x,y)
    elif flag==2:
        return 1 - cosine_similarity(x,y)
    else:
        return manhattan_distance(x,y)

In [9]:
def predict(X_test,k,flag):
    Y_predict = []
    for index, row in X_test.iterrows():
        dist = {}
        labeldict = {i:0 for i in labels}
        for index1, row1 in df1.iterrows():
            dist[index1] = distance(row,row1,flag)
        
        od = sorted(dist.items(), key=operator.itemgetter(1))
        count = k
        for i,j in od:
            count-=1
            labeldict[df1.iloc[i].Y]+=1
            if count==0:
                break
                
        ans_label=0
        ans_count=-1
        for i,j in labeldict.iteritems():
            if j>=ans_count:
                ans_label=i
                ans_count=j
        Y_predict.append(ans_label)
    return Y_predict

In [ ]:
x_axis = [ i for i in xrange(1,12)]
pe = []
pc = []
pm = []

for j in x_axis:
    pe = predict(X_test,j,1)
    
for j in x_axis:
    pc = predict(X_test,j,2)

# for j in x_axis:
#     pm = predict(X_test,j,3)
    
print pc
print pm

a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2

Name: 59, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3

Name: 11, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3

Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object

a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object

a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1

Name: 123, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1

Name: 123, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8

Name: 68, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8

Name: 68, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2

Name: 80, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object

a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object

a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9

Name: 19, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object

a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object

a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3

Name: 74, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object

a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3

Name: 124, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64

a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica

Name: 2, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object

a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor

Name: 104, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64

a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3

Name: 122, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object

a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica

Name: 14, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object

a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9

Name: 20, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9

Name: 20, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica

Name: 40, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2

Name: 126, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4

Name: 46, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7

Name: 110, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7

Name: 110, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object

a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object

a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object

a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3

Name: 55, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object

a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6

Name: 71, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object

a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object

a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica

Name: 13, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4

Name: 86, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1

Name: 13, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object

a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4

Name: 14, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor

Name: 74, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object

a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica

Name: 75, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.7
b    2.5
c    5.8
d    1.8
Name: 18, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object

a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2

Name: 59, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.8
b    2.7
c    3.9
d    1.2
Name: 59, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object

a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor

Name: 92, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    2.9
c    3.6
d    1.3
Name: 11, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3

Name: 125, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.5
c    1.4
d    0.3
Name: 125, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64

a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1

Name: 123, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.3
b    3.0
c    1.1
d    0.1
Name: 123, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica

Name: 46, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8

Name: 68, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.0
b    3.0
c    4.8
d    1.8
Name: 68, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2

Name: 80, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.6
b    3.2
c    1.4
d    0.2
Name: 80, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa

Name: 36, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5

Name: 58, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.9
b    3.0
c    4.2
d    1.5
Name: 58, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa

Name: 53, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.3
b    2.5
c    5.0
d    1.9
Name: 19, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3

Name: 74, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object

a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.5
b    2.3
c    4.0
d    1.3
Name: 74, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3

Name: 124, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object

a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.8
c    1.5
d    0.3
Name: 124, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object

a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5

Name: 66, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    3.0
c    4.5
d    1.5
Name: 66, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object

a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor

Name: 99, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.4
b    3.0
c    4.5
d    1.5
Name: 116, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica

Name: 52, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.4
b    3.4
c    1.5
d    0.4
Name: 37, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3

Name: 122, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object

a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.6
b    3.0
c    4.1
d    1.3
Name: 122, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object

a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64

a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.1
b    3.5
c    1.4
d    0.2
Name: 0, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object

a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object

a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.4
b    2.7
c    5.3
d    1.9
Name: 20, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object

a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2

Name: 126, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    4.8
b    3.4
c    1.6
d    0.2
Name: 126, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4

Name: 46, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.3
b    3.4
c    5.6
d    2.4
Name: 46, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor

Name: 9, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7

Name: 110, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.7
b    3.0
c    5.0
d    1.7
Name: 110, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2

Name: 53, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2

Name: 53, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.1
b    2.8
c    4.7
d    1.2
Name: 53, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3

Name: 55, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3

Name: 55, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.7
b    3.0
c    5.2
d    2.3
Name: 55, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor

Name: 54, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.0
b    2.7
c    5.1
d    1.6
Name: 71, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object

a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3

Name: 62, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    6.9
b    3.2
c    5.7
d    2.3
Name: 62, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object

a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4

Name: 86, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.2
b    2.7
c    3.9
d    1.4
Name: 86, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1

Name: 13, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.5
b                 3
c               5.2
d                 2
Y    Iris-virginica
Name: 56, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.8
c               5.1
d               2.4
Y    Iris-virginica
Name: 57, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.9
b                 3
c               5.1
d               1.8
Y    Iris-virginica
Name: 58, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.1
b            3.8
c            1.6
d            0.2
Y    Iris-setosa
Name: 59, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 60, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.9
b               3.1
c               5.4
d               2.1
Y    Iris-virginica
Name: 61, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b              3
c            1.4
d            0.1
Y    Iris-setosa
Name: 62, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.9
b               3.8
c               6.4
d                 2
Y    Iris-virginica
Name: 63, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.4
c                3.8
d                1.1
Y    Iris-versicolor
Name: 64, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                 6
b               2.2
c                 5
d               1.5
Y    Iris-virginica
Name: 65, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.8
b            3.4
c            1.9
d            0.2
Y    Iris-setosa
Name: 66, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.4
b            3.9
c            1.3
d            0.4
Y    Iris-setosa
Name: 67, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               4.9
b               2.5
c               4.5
d               1.7
Y    Iris-virginica
Name: 68, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.8
b               2.7
c               5.1
d               1.9
Y    Iris-virginica
Name: 69, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               2.8
c               6.7
d                 2
Y    Iris-virginica
Name: 70, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.2
b               3.4
c               5.4
d               2.3
Y    Iris-virginica
Name: 71, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b            3.5
c            1.6
d            0.6
Y    Iris-setosa
Name: 72, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.3
b               2.9
c               6.3
d               1.8
Y    Iris-virginica
Name: 73, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.8
c                4.1
d                1.3
Y    Iris-versicolor
Name: 74, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.1
Y    Iris-virginica
Name: 75, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.6
b                  3
c                4.4
d                1.4
Y    Iris-versicolor
Name: 76, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                4.9
b                2.4
c                3.3
d                  1
Y    Iris-versicolor
Name: 77, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                2.3
c                4.4
d                1.3
Y    Iris-versicolor
Name: 78, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.4
b              3
c            1.3
d            0.2
Y    Iris-setosa
Name: 79, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  6
b                3.4
c                4.5
d                1.6
Y    Iris-versicolor
Name: 80, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.6
c                3.5
d                  1
Y    Iris-versicolor
Name: 81, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.6
b            3.1
c            1.5
d            0.2
Y    Iris-setosa
Name: 82, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 83, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.4
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 84, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               5.6
b               2.8
c               4.9
d                 2
Y    Iris-virginica
Name: 85, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.9
b                3.2
c                4.8
d                1.8
Y    Iris-versicolor
Name: 86, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                3.3
c                4.7
d                1.6
Y    Iris-versicolor
Name: 87, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.1
b                2.5
c                  3
d                1.1
Y    Iris-versicolor
Name: 88, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.4
b                3.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 89, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.2
b               3.6
c               6.1
d               2.5
Y    Iris-virginica
Name: 90, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.3
b                2.5
c                4.9
d                1.5
Y    Iris-versicolor
Name: 91, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  5
b                  2
c                3.5
d                  1
Y    Iris-versicolor
Name: 92, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 93, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.5
b                2.4
c                3.7
d                  1
Y    Iris-versicolor
Name: 94, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.4
b            3.4
c            1.7
d            0.2
Y    Iris-setosa
Name: 95, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               6.4
b               3.1
c               5.5
d               1.8
Y    Iris-virginica
Name: 96, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.6
b                2.9
c                4.6
d                1.3
Y    Iris-versicolor
Name: 97, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a               7.7
b               2.6
c               6.9
d               2.3
Y    Iris-virginica
Name: 98, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.8
b                2.7
c                4.1
d                  1
Y    Iris-versicolor
Name: 99, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            5.8
b              4
c            1.2
d            0.2
Y    Iris-setosa
Name: 100, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.7
b            3.2
c            1.6
d            0.2
Y    Iris-setosa
Name: 101, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                  7
b                3.2
c                4.7
d                1.4
Y    Iris-versicolor
Name: 102, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                6.5
b                2.8
c                4.6
d                1.5
Y    Iris-versicolor
Name: 103, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1

Name: 13, dtype: float64
a                6.9
b                3.1
c                4.9
d                1.5
Y    Iris-versicolor
Name: 104, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a              5
b              3
c            1.6
d            0.2
Y    Iris-setosa
Name: 105, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a                5.7
b                2.9
c                4.2
d                1.3
Y    Iris-versicolor
Name: 106, dtype: object
a    5.2
b    4.1
c    1.5
d    0.1
Name: 13, dtype: float64
a            4.7
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 107, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.2
b               2.8
c               4.8
d               1.8
Y    Iris-virginica
Name: 0, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.5
Y    Iris-virginica
Name: 1, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.1
b                 3
c               5.9
d               2.1
Y    Iris-virginica
Name: 2, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               2.9
c               5.6
d               1.8
Y    Iris-virginica
Name: 3, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.6
b                 3
c               6.6
d               2.1
Y    Iris-virginica
Name: 4, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.1
b                2.9
c                4.7
d                1.4
Y    Iris-versicolor
Name: 5, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 6, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.2
b                2.2
c                4.5
d                1.5
Y    Iris-versicolor
Name: 7, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.6
b            3.6
c              1
d            0.2
Y    Iris-setosa
Name: 8, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.6
c                4.4
d                1.2
Y    Iris-versicolor
Name: 9, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.1
b                  3
c                4.6
d                1.4
Y    Iris-versicolor
Name: 10, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.6
b                2.5
c                3.9
d                1.1
Y    Iris-versicolor
Name: 11, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.5
b               3.2
c               5.1
d                 2
Y    Iris-virginica
Name: 12, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               2.7
c               4.9
d               1.8
Y    Iris-virginica
Name: 13, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b                 3
c               6.1
d               2.3
Y    Iris-virginica
Name: 14, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.7
b            4.4
c            1.5
d            0.4
Y    Iris-setosa
Name: 15, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.4
b               2.8
c               6.1
d               1.9
Y    Iris-virginica
Name: 16, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.4
b            2.9
c            1.4
d            0.2
Y    Iris-setosa
Name: 17, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.8
b               3.2
c               5.9
d               2.3
Y    Iris-virginica
Name: 18, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.8
b                 3
c               5.5
d               2.1
Y    Iris-virginica
Name: 19, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.7
b                3.1
c                4.4
d                1.4
Y    Iris-versicolor
Name: 20, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.5
b                2.5
c                  4
d                1.3
Y    Iris-versicolor
Name: 21, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  6
b                2.2
c                  4
d                  1
Y    Iris-versicolor
Name: 22, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b            3.1
c            1.6
d            0.2
Y    Iris-setosa
Name: 23, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.8
c            1.9
d            0.4
Y    Iris-setosa
Name: 24, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.3
c            1.7
d            0.5
Y    Iris-setosa
Name: 25, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.7
c            1.5
d            0.4
Y    Iris-setosa
Name: 26, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.2
b                 3
c               5.8
d               1.6
Y    Iris-virginica
Name: 27, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.2
b            3.5
c            1.5
d            0.2
Y    Iris-setosa
Name: 28, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.6
b            3.4
c            1.4
d            0.3
Y    Iris-setosa
Name: 29, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               3.2
c               5.3
d               2.3
Y    Iris-virginica
Name: 30, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.4
c            1.6
d            0.4
Y    Iris-setosa
Name: 31, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               7.7
b               3.8
c               6.7
d               2.2
Y    Iris-virginica
Name: 32, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.2
b                2.9
c                4.3
d                1.3
Y    Iris-versicolor
Name: 33, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.7
b                  3
c                4.2
d                1.2
Y    Iris-versicolor
Name: 34, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.2
b            3.4
c            1.4
d            0.2
Y    Iris-setosa
Name: 35, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.6
c            1.4
d            0.2
Y    Iris-setosa
Name: 36, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.9
b            3.1
c            1.5
d            0.1
Y    Iris-setosa
Name: 37, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.4
b            3.2
c            1.3
d            0.2
Y    Iris-setosa
Name: 38, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.3
b            3.7
c            1.5
d            0.2
Y    Iris-setosa
Name: 39, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.1
b               2.6
c               5.6
d               1.4
Y    Iris-virginica
Name: 40, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                5.6
b                2.7
c                4.2
d                1.3
Y    Iris-versicolor
Name: 41, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                6.8
b                2.8
c                4.8
d                1.4
Y    Iris-versicolor
Name: 42, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.1
b            3.4
c            1.5
d            0.2
Y    Iris-setosa
Name: 43, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.7
b            3.8
c            1.7
d            0.3
Y    Iris-setosa
Name: 44, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a              5
b            3.5
c            1.3
d            0.3
Y    Iris-setosa
Name: 45, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.1
b                 3
c               4.9
d               1.8
Y    Iris-virginica
Name: 46, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               5.7
b               2.5
c                 5
d                 2
Y    Iris-virginica
Name: 47, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  6
b                2.9
c                4.5
d                1.5
Y    Iris-versicolor
Name: 48, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.3
b               3.3
c                 6
d               2.5
Y    Iris-virginica
Name: 49, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.9
b               3.1
c               5.1
d               2.3
Y    Iris-virginica
Name: 50, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.7
b               3.3
c               5.7
d               2.1
Y    Iris-virginica
Name: 51, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a               6.4
b               2.8
c               5.6
d               2.2
Y    Iris-virginica
Name: 52, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            4.8
b              3
c            1.4
d            0.3
Y    Iris-setosa
Name: 53, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a                  5
b                2.3
c                3.3
d                  1
Y    Iris-versicolor
Name: 54, dtype: object
a    5.4
b    3.9
c    1.7
d    0.4
Name: 14, dtype: float64
a            5.5
b            3.5
c            1.3
d            0.2
Y    Iris-setosa
Name: 55, dtype: object